version: '3.8'
services:
  backend:
    container_name: rust_backend
    build:
      context: .
      dockerfile: Dockerfile
    image: rust:1.82.0-bookworm
    env_file: .env
    restart: always
    tty: true
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis

  db:
    container_name: rust_db
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: appdb
    ports:
      - 3306:3306

  redis:
    container_name: rust_redis
    image: redis:latest