[package]
name = "server-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
server-domain = { path = "../server-domain" }
server-infra = { path = "../server-infra" }
server-usecase = { path = "../server-usecase" }