[package]
name = "controller"
version = "0.1.0"
edition = "2021"

[dependencies]
usecase = { path = "../usecase" }
axum = "0.7.9"
tokio = { version = "1.41.1", features = ["full"] }
serde_json = "1.0.133"
shaku = "0.6.2"
shaku_derive = "0.6.1"
tower = "0.5.1"
